CC=gcc

caesar_cipher:
	$(CC) caesar_cipher.c -o caesar_cipher
	
frequency_analysis:
	$(CC) frequency_analysis.c -o frequency_analysis

carta_cipher:
	$(CC) carta_cipher.c -o carta_cipher

clean_caesar_cipher:
	rm misterio_output.txt caesar_cipher

clean_frequency_analysis:
	rm frequency_output.txt frequency_analysis

clean_carta_cipher:
	rm carta_output.txt carta_cipher