CC=gcc

xor_cipher:
	$(CC) xor_cipher.c -o xor_cipher
	
rc4:
	$(CC) rc4.c -o rc4

clean_xor_cipher:
	rm xor_cipher

clean_rc4:
	rm rc4

clean_decifrado_xor:
	rm decifrado_xor_a.txt 
	
clean_decifrado:
	rm decifrado.txt
