CC=gcc

cifra_xor:
	$(CC) cifra_xor.c -o cifra_xor
	
rc4:
	$(CC) rc4.c -o rc4

clean_cifra_xor:
	rm cifra_xor

clean_rc4:
	rm rc4

clean_decifrado_xor:
	rm decifrado_xor_a.txt 
	
clean_decifrado:
	rm decifrado.txt
