CC=gcc

vigenere_cipher:
	$(CC) vigenere_cipher.c -o vigenere_cipher
	
crack:
	$(CC) crack.c -o crack

clean_vigenere_cipher:
	rm vigenere_cipher

clean_crack:
	rm crack

clean_poema_cifrado:
	rm poema_cifrado_com_tabela.txt poema_cifrado_sem_tabela.txt

clean_poema_decifrado:
	rm poema_decifrado_com_tabela.txt poema_decifrado_sem_tabela.txt
	
clean_misterio:
	rm misterio_output.txt
